### ISSUE TITLE
Prevent Autoplay

### ISSUE THREAD

**Issue by Tallmios** [YePpHa/maia-yt#72] opened 2017-10-27 11:08 UTC
I would like to see this feature implemented. It was, in my opinion, one of the most useful qualities of the old YouTube Center.

**Comment by YePpHa** [comment] 2017-10-27 11:24
It's a duplicate of #17. It's already available in the alpha version. Check https://github.com/YePpHa/maia-yt/projects/1 for what's been made.

**Closed by YePpHa** 2017-10-27 11:24 UTC
Labels: duplicate
